export const finalSpaceCharacters = [
  {
    id: "welcome",
    screenName: "Welcome Screen",
    thumb: "/images/welcome.png",
    isDraggable: true,
    isMandatory: true,
    description: "Introduction to the lending service and process overview.",
  },
  {
    id: "personal_info",
    screenName: "Personal Information Screen",
    thumb: "/images/personal_info.png",
    isDraggable: true,
    isMandatory: true,
    description: "Collect personal details and verify identity.",
  },
  {
    id: "employment_income",
    screenName: "Employment and Income Information Screen",
    thumb: "/images/employment_income.png",
    isDraggable: false,
    isMandatory: true,
    description:
      "Details about employment status, income sources, and employer.",
  },
  {
    id: "credit_info",
    screenName: "Credit Information Screen",
    thumb: "/images/credit_info.png",
    isDraggable: false,
    isMandatory: true,
    description: "Consent for credit check and display of credit score.",
  },
  {
    id: "loan_details",
    screenName: "Loan Details Screen",
    thumb: "/images/loan_details.png",
    isDraggable: false,
    isMandatory: true,
    description: "Select loan amount, term, and view repayment details.",
  },
  {
    id: "loan_purpose",
    screenName: "Purpose of Loan Screen",
    thumb: "/images/loan_purpose.png",
    isDraggable: true,
    isMandatory: true,
    description: "Specify the reason for the loan.",
  },
  {
    id: "collateral_info",
    screenName: "Collateral Information Screen",
    thumb: "/images/collateral_info.png",
    isDraggable: true,
    isMandatory: true,
    description: "Provide details and valuation of collateral.",
  },
  {
    id: "financial_obligations",
    screenName: "Financial Obligations Screen",
    thumb: "/images/financial_obligations.png",
    isDraggable: false,
    isMandatory: true,
    description: "Disclose existing debts and monthly expenses.",
  },
  {
    id: "terms_conditions",
    screenName: "Terms and Conditions Screen",
    thumb: "/images/terms_conditions.png",
    isDraggable: false,
    isMandatory: true,
    description: "Detailed terms of the loan agreement.",
  },
  {
    id: "document_upload",
    screenName: "Document Upload Screen",
    thumb: "/images/document_upload.png",
    isDraggable: false,
    isMandatory: true,
    description: "Upload required documents for verification.",
  },
  {
    id: "review_confirmation",
    screenName: "Review and Confirmation Screen",
    thumb: "/images/review_confirmation.png",
    isDraggable: true,
    isMandatory: true,
    description: "Summary and confirmation of provided information.",
  },
  {
    id: "digital_signature",
    screenName: "Digital Signature Screen",
    thumb: "/images/digital_signature.png",
    isDraggable: true,
    isMandatory: true,
    description: "Electronically sign the loan agreement.",
  },
  {
    id: "verification_approval",
    screenName: "Verification and Approval Screen",
    thumb: "/images/verification_approval.png",
    isDraggable: true,
    isMandatory: true,
    description: "Status updates and additional information requests.",
  },
  {
    id: "disbursement_info",
    screenName: "Disbursement Information Screen",
    thumb: "/images/disbursement_info.png",
    isDraggable: true,
    isMandatory: true,
    description: "Details on fund disbursement and transfer.",
  },
  {
    id: "customer_support",
    screenName: "Customer Support Screen",
    thumb: "/images/customer_support.png",
    isDraggable: true,
    isMandatory: true,
    description: "Contact support, FAQs, and help resources.",
  },
];

export const idProofs = [
  {
    id: "text",
    label: "Text Input",
    placeholder: "Enter text here",
    maxlength: 50,
    minlength: 3,
    required: true,
    disabled: false,
    readonly: false,
    value: "",
  },
  {
    id: "voter",
    label: "Voter ID Card",
    dependableField: [
      {
        id: "aadhaarVoter",
        label: "Aadhaar Voter Card",
      },
      {
        id: "panVoter",
        label: "PAN Voter Card",
      },
    ],
  },
  {
    id: "number",
    label: "Number Input",
    placeholder: "Enter a number",
    required: true,
    disabled: false,
    readonly: false,
    value: "",
  },
  {
    id: "radio",
    label: "Radio Button",
    required: true,
    disabled: false,
    readonly: false,
  },
  {
    id: "checkbox",
    label: "Checkbox",
    required: true,
    disabled: false,
    readonly: false,
  },
  {
    id: "date",
    label: "Date Input",
    placeholder: "Select a date",
    required: true,
    disabled: false,
    readonly: false,
    value: "",
  },
  {
    id: "select",
    label: "Select Dropdown",
    required: true,
    disabled: false,
    readonly: false,
    value: "",
  },
  {
    id: "textarea",
    label: "Textarea",
    placeholder: "Enter text here",
    maxlength: 200,
    minlength: 10,
    required: true,
    disabled: false,
    readonly: false,
    value: "",
  },
  {
    id: "header",
    label: "Header",
  },
];
